# Generated by Django 3.1.3 on 2022-05-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='deleted_status',
            new_name='visibility_status',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='deleted_status',
            new_name='visibility_status',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
    ]
