# Generated by Django 3.1.3 on 2022-05-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220510_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
