# Generated by Django 3.1.3 on 2022-05-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_alentest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alentest',
        ),
    ]
